# Generated by Django 5.0.4 on 2024-04-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_test_question_test_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_id', models.CharField(blank=True, max_length=50, null=True)),
                ('student_answer', models.CharField(max_length=100)),
                ('student_grade', models.IntegerField(blank=True, editable=False)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='core.test')),
            ],
        ),
    ]
