# Generated by Django 5.0.4 on 2024-05-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student_grade',
            field=models.IntegerField(default=0),
        ),
    ]
