# Generated by Django 5.0.4 on 2024-04-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_grade_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student_answer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
