# Generated by Django 5.0.4 on 2024-05-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_grade_student_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='student_answer',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
