# Generated by Django 5.0.4 on 2024-05-07 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_grade_student_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='answers_false',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='answers_true',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='n_cheating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='student_grade_final',
            field=models.IntegerField(default=0),
        ),
    ]
